FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/app

#============================

FROM alpine:3.21

WORKDIR /app

COPY --from=builder /app/server .
COPY configs ./configs

ENV CONFIG_PATH=./configs/server/local.yaml

EXPOSE 8080

CMD ["./server"]
