# сколько рабочих процессов (worker) запустить
worker_processes auto;

# здесь настраивается, как воркеры принимают подключения.
events {
    # максимум одновременных соединений, которые может держать ОДИН воркер
    worker_connections 1024;
}


# главные настройки HTTP
http {
    # ведение логов
    log_format main '$remote_addr - [$time_local] '
                '"$request" $status $body_bytes_sent '
                'rt=$request_time uct="$upstream_connect_time" '
                'urt="$upstream_response_time"';

    access_log /var/log/nginx/access.log main;

    # сжимает ответ, если клиент поддерживает gzip (проверяется по заголовку Accept-Encoding)
    gzip on;
    gzip_types text/plain text/css application/json
               application/javascript text/xml application/xml;
    gzip_min_length 1024;      # не жать совсем мелкое (накладные расходы не окупятся)
    gzip_comp_level 5;         # 1 (быстро) … 9 (сильно, но дорого по CPU)

    # ограничение количества запросов от одного IP (для защиты от DDoS)
    # $binary_remote_addr - IP-адрес клиента в бинарном виде (4 байта для IPv4, 16 байт для IPv6)
    # zone=api_limit:10m - создаем зону памяти для хранения состояния лимита (10 мегабайт)
    # rate=10r/s - разрешаем не более 10 запросов в секунду
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    # какой файл с типами MIME подключать (для Content-Type)
    include /etc/nginx/mime.types;

    # какой Content-Type ставить, если в mime.types не нашлось совпадения по расширению файла.
    default_type application/octet-stream;

    # sendfile позволяет nginx отдавать файлы напрямую из файловой системы в сокет, минуя лишние копирования через память
    sendfile on;

    # сколько секунд держать открытым бездействующее (keep-alive)
    keepalive_timeout 65;

    # какой файл с настройками виртуальных хостов подключать (server { ... })
    include /etc/nginx/conf.d/*.conf;
}
